# Generated by Django 4.0.1 on 2022-01-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='amount_of_quran',
            field=models.CharField(blank=True, choices=[('complete', 'complete'), ('incomplete', 'incomplete')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.CharField(blank=True, choices=[('educated', 'educated'), ('uneducated', 'uneducated'), ('student', 'student')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='hobby',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='quran_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True),
        ),
    ]
