# Generated by Django 4.0.1 on 2022-01-15 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('die_date_in_higri', models.CharField(max_length=250)),
                ('info', models.TextField()),
                ('religious_view', models.TextField()),
                ('mazhab_fekhy', models.TextField()),
                ('etgah_almofaser_fe_tafseroh', models.TextField()),
                ('manhag_almofaser', models.TextField()),
                ('relations_tree', models.TextField()),
                ('knowledge', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('numbers_of_verses', models.PositiveIntegerField()),
                ('madanya_or_makya', models.CharField(choices=[(1, 'مكية'), (2, 'مدنية')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('info', models.TextField()),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran.surah')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('from_verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_verses', to='quran.verse')),
                ('to_verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_verses', to='quran.verse')),
            ],
        ),
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran.author')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran.verse')),
            ],
        ),
    ]
