# Generated by Django 4.0.1 on 2022-01-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surah',
            name='madanya_or_makya',
            field=models.CharField(choices=[('مكية', 'مكية'), ('مدنية', 'مدنية')], max_length=8),
        ),
    ]
