# Generated by Django 4.0.1 on 2022-01-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0002_alter_surah_madanya_or_makya'),
    ]

    operations = [
        migrations.AddField(
            model_name='surah',
            name='numbers_of_chars',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surah',
            name='numbers_of_words',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surah',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
